[formatting]
align_comments       = true
align_entries        = true
allowed_blank_lines  = 1
array_auto_collapse  = false
array_auto_expand    = false
array_trailing_comma = true
compact_arrays       = true
indent_string        = "\t"
reorder_arrays       = true
reorder_keys         = true
